### ISSUE TITLE
Allow partials in Markdown

### ISSUE THREAD

**Issue by jongunter** [docpad/docpad-plugin-partials#30]
I'd like to use a partial in a markdown page/post, rather than a .html.eco page/post.

**Comment by RobLoach** [comment]
Native Markdown does not have partial support, would need to do something like....

`.html.md.eco`

**Comment by jongunter** [comment]
Yeah that's what I'm doing right now. Works fine, but it would be awesome if it could be implemented in the future. 

Thanks for your help!

**Comment by balupton** [comment]
https://docpad.org/plugin/text is the other option
